### ISSUE TITLE
Introduce option to run IDS with fixed search depth

### ISSUE THREAD

**Issue by thomaskeller79** [prost-planner/prost#99]
Results are often hard to compare because the learning of IDS is non-deterministic but influences planner performance significantly. In this issue, we'd like to replace the learned max search depth of IDS with either a formula (preferred yet harder option) or a command line parameter that allows to set a search depth that is used.

**Comment by geisserf** [comment]
A possible robust approach is to first determine which factors contribute to the search depth of IDS and then try to set a parameter that is relative to these factors.

Anecdotally the branching factor and the complexity of the state transition function (which also depends on whether we can cache or not) play a major role in determining the depth of the IDS, but maybe we can determine that more empirically.

A second question is also how do to deal with problems where we disable caching after some time. In such cases it can happen that the computation time of the IDS is too long because computing state transitions takes much longer than before.

**Comment by thomaskeller79** [comment]
I was just thinking of setting this via command line, but I agree that coming up with a formula that is based on task properties would be even better. The branching factor of actions is certainly the most important factor. As we compute IDS in a determinization, the branching factor of outcomes should not play a crucial role, but there are certainly other factors (e.g., if CPFs, reward and action preconditions have been precomputed or not). It would be good to start working on this issue by collecting some data on this question.

**Comment by thomaskeller79** [comment]
The issue has  been resolved in 88fec2151f9be2a96ef00d76154654745b94cbdd
